<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- <TargetFramework>net11.0</TargetFramework> -->
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Workforce.Domain/Workforce.Domain.csproj" />
  </ItemGroup>

</Project>
