<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <!-- <TargetFramework>net11.0</TargetFramework> -->
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Workforce.Migrator-626c1470-9255-4895-9d02-37ff5ac039f5</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../aspire/Workforce.ServiceDefaults/Workforce.ServiceDefaults.csproj" />
    <ProjectReference Include="../Workforce.Infrastructure/Workforce.Infrastructure.csproj" />
  </ItemGroup>
</Project>
