<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <!-- <TargetFramework>net11.0</TargetFramework> -->
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" />
    <PackageReference Include="Microsoft.Extensions.ServiceDiscovery.Yarp" />
    <PackageReference Include="Yarp.ReverseProxy" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../aspire/Workforce.ServiceDefaults/Workforce.ServiceDefaults.csproj" />
    <ProjectReference Include="../Workforce.Web.Client/Workforce.Web.Client.csproj" />
  </ItemGroup>

</Project>
