// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Workforce.Infrastructure;

#nullable disable

namespace Workforce.Migrator.Migrations;

[DbContext(typeof(WorkforceDbContext))]
[Migration("20260724202351_Initial")]
partial class _20260724202351_Initial
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "11.0.0-preview.6.26359.118")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.HasSequence("employeeskillseq")
            .IncrementsBy(10);

        modelBuilder.Entity("Workforce.Domain.Model.Employee", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier")
                    .HasColumnName("Id")
                    .HasDefaultValueSql("NEWSEQUENTIALID()");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)")
                    .HasColumnName("Email");

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasMaxLength(75)
                    .HasColumnType("nvarchar(75)")
                    .HasColumnName("FirstName");

                b.Property<string>("LastName")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)")
                    .HasColumnName("LastName");

                b.HasKey("Id");

                b.ToTable("Employees");
            });

        modelBuilder.Entity("Workforce.Domain.Model.Skill", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier")
                    .HasColumnName("Id")
                    .HasDefaultValueSql("NEWSEQUENTIALID()");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(75)
                    .HasColumnType("nvarchar(75)")
                    .HasColumnName("Name");

                b.HasKey("Id");

                b.ToTable("Skills");
            });

        modelBuilder.Entity("Workforce.Domain.Model.Employee", b =>
            {
                b.OwnsMany("Workforce.Domain.Model.EmployeeSkill", "Skills", b1 =>
                    {
                        var id = b1.Property<long>("Id")
                            .ValueGeneratedOnAdd()
                            .HasColumnType("bigint");

                        SqlServerPropertyBuilderExtensions.UseHiLo(id, "employeeskillseq");

                        b1.Property<Guid>("EmployeeId")
                            .HasColumnType("uniqueidentifier");

                        b1.Property<int>("Proficiency")
                            .HasColumnType("int");

                        b1.Property<Guid>("SkillId")
                            .HasColumnType("uniqueidentifier");

                        b1.Property<int>("YearsOfExperience")
                            .HasColumnType("int");

                        b1.HasKey("Id");

                        b1.HasIndex("EmployeeId");

                        b1.HasIndex("SkillId");

                        b1.ToTable("EmployeeSkill");

                        b1.WithOwner()
                            .HasForeignKey("EmployeeId");

                        b1.HasOne("Workforce.Domain.Model.Skill", null)
                            .WithMany()
                            .HasForeignKey("SkillId")
                            .OnDelete(DeleteBehavior.Cascade)
                            .IsRequired();
                    });

                b.Navigation("Skills");
            });
#pragma warning restore 612, 618
    }
}
